spring.application.name=smart-devops-assistant
spring.main.web-application-type=REACTIVE
server.port=8389

spring.ai.openai.api-key=YOUR_OPENAI_API_KEY
spring.ai.openai.base-url=http://localhost:12434/engines
spring.ai.openai.chat.options.model=ai/gemma3

git.owner=ankit.agrahari
git.repo.name=smart-devops-assistant
git.api.url=https://api.github.com/

logging.level.root= debug

slack.incoming.webhook.url=https://hooks.slack.com/services/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